# generate sitemap
name: update-sitemap
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/update.txt'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
      - name: Check out repo code
        uses: actions/checkout@v3
      - shell: bash
        name: Generate a new site map
        run: |
          chmod +x /home/runner/work/icapito-database/icapito-database/scripts/sitemap.sh
          chmod +x /home/runner/work/icapito-database/icapito-database/scripts/feedrss.sh
          /home/runner/work/icapito-database/icapito-database/scripts/sitemap.sh
          /home/runner/work/icapito-database/icapito-database/scripts/feedrss.sh
          git config --local user.name "githubaction"
          git add ./db/sitemap.xml
          git add ./db/feed-rss.xml
          git add ./backup/*
          git commit -m "Update sitemap"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
          exit 0
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
