# generate sitemap
name: update-sitemap
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
      paths:
        - 'icapito-database/scripts/update.txt'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - shell: bash
        name: Generate a new site map
        run: |
          chmod +x /home/runner/work/icapito-database/icapito-database/scripts/sitemap.sh
          /home/runner/work/icapito-database/icapito-database/scripts/sitemap.sh
          git config --local user.name "githubaction"
          git add ./docs
    git commit -m "Updating the repository GitHub html pages in the docs folder"
          exit 0
